// Transforms the vendored d3-celestial data (BSD, github.com/ofrohn/d3-celestial)
// into src/sky/sky.generated.ts. Run with: npm run build:sky
//
// Stars come as [RA°, Dec°] with HIP ids and magnitudes (no proper names — we
// attach a curated set below). Constellation figures come as coordinate
// polylines keyed by IAU abbreviation, joined to full names via constellations.json.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const dataDir = join(here, '..', 'data', 'd3-celestial')
const outFile = join(here, '..', 'src', 'sky', 'sky.generated.ts')

const MAG_CUTOFF = 7.0
const STARS_FILE = 'stars.8.json' // deep catalog (to mag 8); we filter below

// Approximate a star's RGB color from its B-V color index (blue -> white -> red).
function bvToRGB(bvRaw) {
  const anchors = [
    [-0.4, [155, 176, 255]],
    [-0.2, [170, 191, 255]],
    [0.0, [202, 216, 255]],
    [0.2, [248, 247, 255]],
    [0.4, [255, 250, 232]],
    [0.6, [255, 244, 214]],
    [0.8, [255, 230, 190]],
    [1.2, [255, 210, 160]],
    [1.6, [255, 185, 130]],
    [2.0, [255, 165, 110]],
  ]
  let v = parseFloat(bvRaw)
  if (!Number.isFinite(v)) v = 0.6
  v = Math.max(-0.4, Math.min(2.0, v))
  for (let i = 0; i < anchors.length - 1; i++) {
    const [b0, c0] = anchors[i]
    const [b1, c1] = anchors[i + 1]
    if (v <= b1) {
      const t = (v - b0) / (b1 - b0)
      return [0, 1, 2].map((k) => Math.round(c0[k] + (c1[k] - c0[k]) * t))
    }
  }
  return anchors[anchors.length - 1][1]
}

// Curated proper names for notable stars, keyed by Hipparcos id. Only these get
// hover labels — deliberately a recognizable handful, not 1,600 designations.
const NAMES = {
  32349: 'Sirius', 30438: 'Canopus', 69673: 'Arcturus', 91262: 'Vega',
  24608: 'Capella', 24436: 'Rigel', 37279: 'Procyon', 27989: 'Betelgeuse',
  7588: 'Achernar', 68702: 'Hadar', 97649: 'Altair', 60718: 'Acrux',
  21421: 'Aldebaran', 80763: 'Antares', 65474: 'Spica', 37826: 'Pollux',
  113368: 'Fomalhaut', 102098: 'Deneb', 62434: 'Mimosa', 49669: 'Regulus',
  33579: 'Adhara', 36850: 'Castor', 61084: 'Gacrux', 85927: 'Shaula',
  25336: 'Bellatrix', 25428: 'Elnath', 26311: 'Alnilam', 26727: 'Alnitak',
  25930: 'Mintaka', 54061: 'Dubhe', 34444: 'Wezen', 90185: 'Kaus Australis',
  67301: 'Alkaid', 31681: 'Alhena', 11767: 'Polaris', 30324: 'Mirzam',
  46390: 'Alphard', 50583: 'Algieba', 9884: 'Hamal', 92855: 'Nunki',
  3179: 'Schedar', 746: 'Caph', 72607: 'Kochab', 57632: 'Denebola',
  14576: 'Algol', 65378: 'Mizar', 17702: 'Alcyone', 15863: 'Mirfak',
  100751: 'Peacock', 109268: 'Alnair', 68933: 'Menkent', 86228: 'Sargas',
}

const normLon = (ra) => (ra < 0 ? ra + 360 : ra)
const r3 = (n) => Math.round(n * 1000) / 1000
const r2 = (n) => Math.round(n * 100) / 100

function centroid(coords) {
  let x = 0, y = 0, z = 0
  const DEG = Math.PI / 180
  for (const [lon, lat] of coords) {
    const la = lat * DEG, lo = lon * DEG
    x += Math.cos(la) * Math.cos(lo)
    y += Math.cos(la) * Math.sin(lo)
    z += Math.sin(la)
  }
  const lat = Math.atan2(z, Math.hypot(x, y)) * (180 / Math.PI)
  let lon = Math.atan2(y, x) * (180 / Math.PI)
  if (lon < 0) lon += 360
  return { lon: r3(lon), lat: r3(lat) }
}

const starsRaw = JSON.parse(readFileSync(join(dataDir, STARS_FILE), 'utf8')).features
const linesRaw = JSON.parse(readFileSync(join(dataDir, 'constellations.lines.json'), 'utf8')).features
const conRaw = JSON.parse(readFileSync(join(dataDir, 'constellations.json'), 'utf8')).features

const nameByDesig = {}
for (const f of conRaw) nameByDesig[f.properties.desig] = f.properties.name

const stars = starsRaw
  .filter((f) => f.properties.mag <= MAG_CUTOFF)
  .map((f) => {
    const [ra, dec] = f.geometry.coordinates
    const [r, g, b] = bvToRGB(f.properties.bv)
    const s = {
      id: `hip${f.id}`,
      lon: r3(normLon(ra)),
      lat: r3(dec),
      mag: r2(f.properties.mag),
      color: `rgb(${r}, ${g}, ${b})`,
    }
    if (NAMES[f.id]) s.name = NAMES[f.id]
    return s
  })
  .sort((a, b) => a.mag - b.mag)

const constellations = linesRaw.map((f) => {
  const paths = f.geometry.coordinates.map((path) => path.map(([ra, dec]) => [r3(normLon(ra)), r3(dec)]))
  const allVerts = paths.flat()
  return { name: nameByDesig[f.id] || f.id, paths, center: centroid(allVerts) }
})

const header = `// AUTO-GENERATED by scripts/build-sky.mjs — do not edit by hand.
// Source: d3-celestial (BSD-3-Clause), https://github.com/ofrohn/d3-celestial
// Star catalog filtered to magnitude <= ${MAG_CUTOFF} (${stars.length} stars);
// all ${constellations.length} constellation figures. Run: npm run build:sky
import type { Star, Constellation } from './constellations'
`

const body =
  header +
  `\nexport const STARS: Star[] = ${JSON.stringify(stars)}\n\n` +
  `export const CONSTELLATIONS: Constellation[] = ${JSON.stringify(constellations)}\n`

writeFileSync(outFile, body)
console.log(`Wrote ${stars.length} stars, ${constellations.length} constellations -> ${outFile}`)
console.log(`Named stars: ${stars.filter((s) => s.name).length}`)
